# This workflow will:
# - do a clean install of node dependencies
# - build the source code
# - run tests across different versions of node
# See: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: nodejs-ci

on:
  push:
    paths-ignore:
      - ".vscode/**"
      - "*.md"
  pull_request:
    paths-ignore:
      - ".vscode/**"
      - "*.md"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run test
