# Workflow for creating a new release and publishing it to NPM.
name: npm-release-publish

on:
  push:
    tags:
      - "v*" # Trigger the workflow on push tag events matching glob (e.g. v1.0, v20.15.10)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          # "ref" specifies the branch to check out.
          # "github.event.release.target_commitish" specifies the target branch of the release.
          ref: ${{ github.event.release.target_commitish }}

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
        env:
          # GITHUB_TOKEN is automatically provided by actions.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/

      - name: Clean install of dependencies, build, and test
        # Avoid `yarn.lock` changes.
        run: |
          yarn install --frozen-lockfile
          yarn build
          yarn test

      - name: Setup git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Upgrade version in package.json to release tag version
        run: yarn version ${{ github.event.release.tag_name }}

      - name: Publish to NPM via auth token
        run: yarn publish
        env:
          # Ensure NPM_TOKEN is added to repository secrets.
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push version changes
        run: git push
        env:
          # GITHUB_TOKEN is automatically provided by actions.
          github-token: ${{ secrets.GITHUB_TOKEN }}
