# Workflow for creating a new release and publishing it to NPM.
name: npm-release-publish

on:
  release:
    # Trigger the workflow when a release is published
    # This specifies that the build will be triggered when we publish a release
    types: [published]

jobs:
  publish:
    name: Publish the release to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          # "ref": the branch to check out.
          # "github.event.release.target_commitish": the target branch of the release
          ref: ${{ github.event.release.target_commitish }}
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - name: Clean install of dependencies, build, and test
        # Avoid `yarn.lock` changes.
        run: |
          yarn install --frozen-lockfile
          yarn build
          yarn test
      - name: Upgrade version in package.json to release tag version
        run: yarn version --new-version ${{ github.event.release.tag_name }} --no-git-tag-version
      - name: Publish to NPM via auth token
        run: yarn publish
        env:
          # Ensure NPM_TOKEN is added to repository secrets.
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Configure git and push version changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git push
        env:
          # GITHUB_TOKEN is automatically provided by actions.
          github-token: ${{ secrets.GITHUB_TOKEN }}
      #     # Create a local variable containing the pushed tag name
      #   # (extracted from "refs/tags/{{tagName}}" via parameter expansion)
      # - name: Set output
      #   id: vars
      #   run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
