# Workflow for creating a new release.
name: Create Release

on:
  push:
    # Trigger the workflow when matched against tags
    tags:
      - "v*" # Push events to matching v* (e.g. v1.0, v20.15.10)

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
        env:
          # GITHUB_TOKEN is automatically provided by actions.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
