# Workflow for building and testing the project.
name: test-build

on:
  push:
    paths-ignore:
      - .github/**
      - .vscode/**
      - "*.md"
  pull_request:
    paths-ignore:
      - .github/**
      - .vscode/**
      - "*.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org/
      - name: Install deps, build, and test
        run: |
          yarn install --frozen-lockfile
          yarn build
          yarn test
